#!/bin/bash
echo "Изменяем hostname VM"
hostnamectl set-hostname wp-slave 
systemctl restart systemd-hostnamed
echo "Устанавливаем статический IP адрес"
nmcli connection show
nmcli con add type ethernet con-name 'static-ip' ifname enp0s3 ipv4.method manual ipv4.addresses 192.168.0.109/24 gw4 192.168.0.1
nmcli con mod static-ip ipv4.dns 8.8.8.8
nmcli con up id 'static-ip'
echo "Применяем правила IPTABLES"
bash ./rules.v4
wget https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-386.tar.gz
tar -xvf node_exporter-1.4.0.linux-386.tar.gz
sudo mv node_exporter-1.4.0.linux-386/node_exporter /usr/local/bin/
sudo useradd -rs /bin/false node_exporter
cp ./node_exporter.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl start node_exporter
sudo systemctl enable node_exporter
echo "Устанавливаем базу данных Mysql"
apt install mysql-server-8.0 -y
cp ./mysqld.cnf /etc/mysql/mysql.conf.d/mysqld.cnf
systemctl restart mysql
bash ./mysql_scripts
echo "ПОДГОТОВКА SLAVE DB ОКОНЧЕНА"

